//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente_Curso
    {
        public int ID { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> CursoID { get; set; }
        public Nullable<int> DocenteID { get; set; }
    
        public virtual Docente Docente { get; set; }
    }
}
