//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente_Curso
    {
        public int ID { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> CursoID { get; set; }
        public Nullable<int> DocenteID { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
