using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    using ProyectoTFI.Models;
    
    public partial class Donacion
    {
        public Donacion()
        {

        }

        public Donacion(DonacionViewModel pDonacionViewModel)
        {
            NombreEmpresa = pDonacionViewModel.NombreEmpresa;
            Email = pDonacionViewModel.Email;
            PrefijoTelefono = pDonacionViewModel.PrefijoTelefono;
            Telefono = pDonacionViewModel.Telefono;
            Monto = pDonacionViewModel.Monto;

            Tarjeta = new Tarjeta(pDonacionViewModel.TipoTarjeta == "Débito"? false : true, pDonacionViewModel.Numero, pDonacionViewModel.FechaCaducidad, pDonacionViewModel.CVV);
        }

        public int ID { get; set; }

        [Required]
        [Display(Name = "Empresa")]
        [StringLength(50)]
        public string NombreEmpresa { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Correo Electrónico")]
        [EmailAddress(ErrorMessage = "El Formato del Correo Electrónico es incorrecto.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "El Formato del Correo Electrónico es incorrecto.")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Prefijo Telefónico")]
        public int PrefijoTelefono { get; set; }

        [Required]
        [Display(Name = "Número de Teléfono")]
        public int Telefono { get; set; }

        [StringLength(5)]
        [Required]
        [Display(Name = "Monto a Donar")]
        public decimal Monto { get; set; }
        public int TarjetaID { get; set; }
    
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
