//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donacion
    {
        public int ID { get; set; }
        public string NombreEmpresa { get; set; }
        public string Email { get; set; }
        public int PrefijoTelefono { get; set; }
        public int Telefono { get; set; }
        public decimal Monto { get; set; }
        public int TarjetaID { get; set; }
    
        public virtual Tarjeta Tarjeta { get; set; }
    }
}
