//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Pregunta_Opcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz_Pregunta_Opcion()
        {
            this.Quiz_Respuesta = new HashSet<Quiz_Respuesta>();
        }
    
        public int ID { get; set; }
        public string DescripcionOpcion { get; set; }
        public Nullable<bool> Correcta { get; set; }
        public Nullable<int> QuizPreguntaID { get; set; }
    
        public virtual Quiz_Pregunta Quiz_Pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz_Respuesta> Quiz_Respuesta { get; set; }
    }
}
