//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Conclusion
    {
        public int ID { get; set; }
        public Nullable<int> Clasificacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Aprobado { get; set; }
        public Nullable<int> QuizCursadaDeAlumno { get; set; }
    }
}
