//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Respuesta
    {
        public int ID { get; set; }
        public Nullable<int> QuizCursadaDeAlumnoID { get; set; }
        public Nullable<int> QuizPreguntaOpcionID { get; set; }
    
        public virtual Quiz_Cursada_de_Alumno Quiz_Cursada_de_Alumno { get; set; }
        public virtual Quiz_Pregunta_Opcion Quiz_Pregunta_Opcion { get; set; }
    }
}
