//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Respuesta
    {
        public int ID { get; set; }
        public Nullable<int> QuizCursadaDeAlumnoID { get; set; }
        public Nullable<int> QuizPreguntaOpcionID { get; set; }
    
        public virtual Quiz_Cursada_de_Alumno Quiz_Cursada_de_Alumno { get; set; }
        public virtual Quiz_Pregunta_Opcion Quiz_Pregunta_Opcion { get; set; }
    }
}
