//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Respuesta
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public int SolicitudID { get; set; }
        public int AdministradorID { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Solicitud_Soporte Solicitud_Soporte { get; set; }
    }
}
