using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.Donacion = new HashSet<Donacion>();
        }

        public Tarjeta(bool pTipo, string pNumero, int pFechaCaducidad, int pCVV)
        {
            this.Donacion = new HashSet<Donacion>();
            Tipo = pTipo;
            Numero = pNumero;
            FechaCaducidad = pFechaCaducidad;
            CVV = pCVV;
        }

        public int ID { get; set; }
        public Nullable<bool> Tipo { get; set; }

        [Required]
        [Display(Name = "Número de Tarjeta")]
        public string Numero { get; set; }

        [Required]
        [Display(Name = "Fecha de Caducidad")]
        public Nullable<int> FechaCaducidad { get; set; }

        [Required]
        [Display(Name = "Código de Seguridad")]
        public Nullable<int> CVV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacion> Donacion { get; set; }
    }
}
