//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTFI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.Donacion = new HashSet<Donacion>();
        }

        public Tarjeta(bool pTipo, string pNumero, int pFechaCaducidad, int pCVV)
        {
            this.Donacion = new HashSet<Donacion>();
            Tipo = pTipo;
            Numero = pNumero;
            FechaCaducidad = pFechaCaducidad;
            CVV = pCVV;
        }

        public int ID { get; set; }
        public Nullable<bool> Tipo { get; set; }
        public string Numero { get; set; }
        public Nullable<int> FechaCaducidad { get; set; }
        public Nullable<int> CVV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donacion> Donacion { get; set; }
    }
}
